### ISSUE TITLE
Cool datasets

### ISSUE THREAD

**Issue by firmai** [jainr3/SECret-Insights#1]
Hi, thanks for the datasets, do you perhaps have the code available where you break the text into these different items, currently I am using regex but it is messy, I wonder if you don't have a primary source or cleaner solution?  

https://github.com/jainr3/SECret-Insights/blob/main/sec_edgar_annual_financial_filings_2021/extracted/1001601_10K_2020_0001493152-21-008913.json

**Comment by jainr3** [comment]
Original data: https://www.kaggle.com/datasets/pranjalverma08/sec-edgar-annual-financial-filings-2021?resource=download&select=raw
https://www.kaggle.com/datasets/chad116/sec-company-facts-all-10q-10k-financial-data

Some parsing: https://github.com/jainr3/SECret-Insights/blob/main/analysis.ipynb

**Comment by firmai** [comment]
Oh no that doesn't parse it, parsing is happening somewhere else, it seems to be reading in already parse files. I am looking for a resource that I can update for a research paper. Thanks for the help though. 

![image](https://user-images.githubusercontent.com/26666267/217263964-b9c9ccc3-c8ff-4f1a-8ea0-bfe1402b3e5f.png)
